import { createClient } from "https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm";
const DATA_KEY="chadFinanceV3";
const CONFIG_KEY="chadFinanceCloudV4";
let client=null,session=null,passphrase="",lastUploaded="",timer=null;
const $=id=>document.getElementById(id);
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function status(msg,type=""){$("cloudStatus").textContent=msg;$("cloudStatus").className=`notice ${type}`.trim()}
function config(){try{return JSON.parse(localStorage.getItem(CONFIG_KEY))||{}}catch{return{}}}
function fill(){const c=config();$("cloudUrl").value=c.url||"";$("cloudAnonKey").value=c.anonKey||"";$("cloudEmail").value=c.email||""}
function saveConfig(){const c={url:$("cloudUrl").value.trim(),anonKey:$("cloudAnonKey").value.trim(),email:$("cloudEmail").value.trim()};localStorage.setItem(CONFIG_KEY,JSON.stringify(c));init();status("Cloud settings saved. Sign in to continue.","success")}
async function init(){fill();const c=config();if(!c.url||!c.anonKey){client=null;status("Cloud sync is not configured.");return}try{client=createClient(c.url,c.anonKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});const r=await client.auth.getSession();session=r.data.session;client.auth.onAuthStateChange((_e,s)=>{session=s;update();if(session&&passphrase)reconcile()});update()}catch(e){status(`Cloud configuration error: ${e.message}`,"error")}}
function update(){if(!client)return status("Cloud sync is not configured.");if(!session)return status("Cloud configured, but you are not signed in.");if(!passphrase)return status(`Signed in as ${session.user.email}. Enter the encryption passphrase.`);status(`Encrypted cloud sync is ready for ${session.user.email}.`,"success")}
async function signIn(){if(!client)return alert("Save the Supabase URL and anon key first.");const email=$("cloudEmail").value.trim();if(!email)return alert("Enter your email address.");const redirectTo=location.origin+location.pathname;const {error}=await client.auth.signInWithOtp({email,options:{emailRedirectTo:redirectTo}});if(error)return status(error.message,"error");status("A sign-in link has been emailed to you. Open it on this device.","success")}
async function signOut(){if(client)await client.auth.signOut();session=null;passphrase="";$("cloudPassphrase").value="";update()}
function b64(bytes){let s="";for(const b of bytes)s+=String.fromCharCode(b);return btoa(s)}
function unb64(s){const b=atob(s),a=new Uint8Array(b.length);for(let i=0;i<b.length;i++)a[i]=b.charCodeAt(i);return a}
async function keyFor(p,salt){const m=await crypto.subtle.importKey("raw",new TextEncoder().encode(p),"PBKDF2",false,["deriveKey"]);return crypto.subtle.deriveKey({name:"PBKDF2",salt,iterations:250000,hash:"SHA-256"},m,{name:"AES-GCM",length:256},false,["encrypt","decrypt"])}
async function encrypt(text,p){const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),key=await keyFor(p,salt),cipher=new Uint8Array(await crypto.subtle.encrypt({name:"AES-GCM",iv},key,new TextEncoder().encode(text)));return{v:1,salt:b64(salt),iv:b64(iv),ciphertext:b64(cipher)}}
async function decrypt(obj,p){const key=await keyFor(p,unb64(obj.salt)),plain=await crypto.subtle.decrypt({name:"AES-GCM",iv:unb64(obj.iv)},key,unb64(obj.ciphertext));return new TextDecoder().decode(plain)}
function localData(){return localStorage.getItem(DATA_KEY)||""}
async function upload(){if(!client||!session||!passphrase)return;const raw=localData();if(!raw)return;status("Encrypting and uploading...");try{const encrypted=await encrypt(raw,passphrase),modified=Date.now();const {error}=await client.from("finance_state").upsert({user_id:session.user.id,encrypted_state:encrypted,client_modified_at:new Date(modified).toISOString(),updated_at:new Date().toISOString()},{onConflict:"user_id"});if(error)throw error;lastUploaded=raw;localStorage.setItem("chadFinanceCloudLastModified",String(modified));status(`Encrypted sync completed at ${new Date().toLocaleTimeString()}.`,"success")}catch(e){status(`Cloud upload failed: ${e.message}`,"error")}}
async function reconcile(){if(!client||!session||!passphrase)return;status("Checking encrypted cloud backup...");try{const {data,error}=await client.from("finance_state").select("encrypted_state,client_modified_at").eq("user_id",session.user.id).maybeSingle();if(error)throw error;const raw=localData();if(!data){await upload();return}const cloudRaw=await decrypt(data.encrypted_state,passphrase),cloudTime=new Date(data.client_modified_at).getTime(),localTime=Number(localStorage.getItem("chadFinanceCloudLastModified")||0);if(cloudTime>localTime&&cloudRaw!==raw){if(confirm("A newer cloud copy was found. Replace the data on this device with the cloud copy?")){localStorage.setItem(DATA_KEY,cloudRaw);localStorage.setItem("chadFinanceCloudLastModified",String(cloudTime));status("Cloud data restored. Reloading...","success");await sleep(500);location.reload()}else status("Cloud download cancelled. Local data was not changed.")}else if(raw!==cloudRaw){await upload()}else{lastUploaded=raw;status("Local and cloud data are already in sync.","success")}}catch(e){status(`Cloud sync failed: ${e.message}. Check the passphrase and setup.`,"error")}}
function watch(){clearInterval(timer);timer=setInterval(()=>{const raw=localData();if(client&&session&&passphrase&&raw&&raw!==lastUploaded)upload()},5000)}
window.addEventListener("DOMContentLoaded",()=>{$("cloudSaveConfigBtn").onclick=saveConfig;$("cloudSignInBtn").onclick=signIn;$("cloudSignOutBtn").onclick=signOut;$("cloudSyncBtn").onclick=()=>{passphrase=$("cloudPassphrase").value;update();reconcile()};$("cloudPassphrase").onchange=()=>{passphrase=$("cloudPassphrase").value;update()};init();watch()});
